//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jan 28 14:22:53 2021 by ROOT version 6.22/00)
//      from the StreamerInfo in file
//      /home/mcgrew/data/dune/output_file_ecal_separate2.root
//////////////////////////////////////////////////////////
#ifndef cell_h
#define cell_h
class cell;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

class cell {

public:
// Nested classes declaration.

public:
// Data Members.
    int         id;          //
    double      z;           //
    double      y;           //
    double      x;           //
    double      l;           //
    double      adc1;        //
    double      tdc1;        //
    double      adc2;        //
    double      tdc2;        //
    int         mod;         //
    int         lay;         //
    int         cel;         //
    std::vector<double> pe_time1;    //
    std::vector<int>    hindex1;     //
    std::vector<double> pe_time2;    //
    std::vector<int>    hindex2;     //

    cell();
    cell(cell && ) = default;
    cell(const cell & );
    virtual ~cell();

};
#endif

// Local Variables:
// mode:c++
// c-basic-offset:4
// compile-command:"$(git rev-parse --show-toplevel)/build/erep-build.sh force"
// End:
