//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jan 28 14:22:53 2021 by ROOT version 6.22/00)
//      from the StreamerInfo in file
//      /home/mcgrew/data/dune/output_file_ecal_separate2.root
//////////////////////////////////////////////////////////

#ifndef digit_h
#define digit_h
class digit;

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include <vector>

class digit {

public:
// Nested classes declaration.

public:
// Data Members.
    std::string      det;         //
    double      x;           //
    double      y;           //
    double      z;           //
    double      t;           //
    double      de;          //
    bool        hor;         //
    std::vector<int> hindex;      //

    digit();
    digit(digit && ) = default;
    digit(const digit & );
    virtual ~digit();

};
#endif

// Local Variables:
// mode:c++
// c-basic-offset:4
// compile-command:"$(git rev-parse --show-toplevel)/build/erep-build.sh force"
// End:
